name: Docker Build & Publish

on:
  push:
    branches:
      - master
  # release:
  #   types: [published]

jobs:
  push:
    name: Push Docker image to Docker Hub
    env:
      PSYCHOPY_VERSION: 2020.2.5
      PYTHON_VERSION: 3.9.0
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push Default image
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            BASE_IMAGE=ubuntu:bionic
            PSYCHOPY_VERSION=${{ env.PSYCHOPY_VERSION }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          tags: |
            aoirint/psychopy:latest
            aoirint/psychopy:${{ env.PSYCHOPY_VERSION }}
            aoirint/psychopy:${{ env.PSYCHOPY_VERSION }}-python${{ env.PYTHON_VERSION }}

      -
        name: Build and push NVIDIA image
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            BASE_IMAGE=nvidia/opengl:base-ubuntu18.04
            PSYCHOPY_VERSION=${{ env.PSYCHOPY_VERSION }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          tags: |
            aoirint/psychopy:nvidia
            aoirint/psychopy:${{ env.PSYCHOPY_VERSION }}-nvidia
            aoirint/psychopy:${{ env.PSYCHOPY_VERSION }}-nvidia-python${{ env.PYTHON_VERSION }}
